### ISSUE TITLE
Implement Localization

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treemapper#11]
Open Issues:

- [ ] still resources not extracted into translation files, e.g. https://github.com/Plant-for-the-Planet-org/treemapper/issues/11#issuecomment-768155939?
- [x] not localized numbers (e.g. tree count > 1.000, tree height and diameter or the size of map downloads etc?)
- [ ] not localized country names (e.g. in downloaded map areas?)
- [x] not localized date values (probably solved at https://github.com/Plant-for-the-Planet-org/treemapper/blob/b871ce981662a4ff360b6032ceccb0b95f2a3455/app/languages/languages.js#L34)

--

- [x] Localization with i18n is completed

However this requires multiple steps.

- [x] Integrate React Native Localize. https://github.com/react-native-community/react-native-localize

- [x] Localize Pages

- [x] Localize Android permission Request texts

- [x] Localize iOS permission Request texts

- [x] Connect this repo to LingoHub and is set to accept PR with translations

---
If a language string has a sentence with  variables; eg:
`Thank you for planting 150 trees.`

It should be translated as one string where 150 becomes a variable.

**Comment by norbertschuler** [comment]
@sagararyal Maybe you could specify which languages the app should support?

**Comment by sagararyal** [comment]
Initially we would like to support en, es, pt-br
and gradually add languages spoken in these countries.

<img width="996" alt="Screen Shot 2020-06-20 at 10 40 42 AM" src="https://user-images.githubusercontent.com/5401575/85206798-b714a700-b324-11ea-9388-41481bd4c60a.png">

**Comment by captainamiedi** [comment]
@sagararyal  Localize Android permission Request texts and Localize iOS permission Request texts cannot be customized. Switch your device language and they are switched as well.

**Comment by norbertschuler** [comment]
I localized the iOS permission strings and created two new project in LingoHub for iOS permission string and for all the i18n resources in our JavaScript code. Currently their are based on the `feature/localization` for testing, but that needs to be changed to the `develop` branch once `feature/localization` got merged.

**Comment by norbertschuler** [comment]
There are no native Android permission strings to be translated within the native Android project, but there are some permission strings to be localized within our JavaScript  code base, e.g.: 

https://github.com/Plant-for-the-Planet-org/treemapper/blob/e08e9782933e23ea90fd720ef18fc962686078c2/app/Components/InventoryOverview/index.js#L135-L150

https://github.com/Plant-for-the-Planet-org/treemapper/blob/e08e9782933e23ea90fd720ef18fc962686078c2/app/Components/RegisterSingleTree/ImageCapturing.js#L73-L78

https://github.com/Plant-for-the-Planet-org/treemapper/blob/e08e9782933e23ea90fd720ef18fc962686078c2/app/Components/CreatePolygon/ImageCapturing.js#L119-L124

**Comment by norbertschuler** [comment]
I don't think the translation task is done yet:
- [ ] still resources not extracted into translation files
- [ ] not localized date values
- [ ] not localized numbers (if any)
- [ ] not localized country names (if wanted)

**Comment by norbertschuler** [comment]
![Species 1](https://user-images.githubusercontent.com/1532418/89916501-de4f6c80-dc21-11ea-9bef-b127a6490c3d.png)![Species 2](https://user-images.githubusercontent.com/1532418/89916507-e14a5d00-dc21-11ea-8383-3e41aacc8605.png)![Tree Inventory 1](https://user-images.githubusercontent.com/1532418/89916533-ead3c500-dc21-11ea-85a2-25e29789ff22.png)![Tree Inventory 2](https://user-images.githubusercontent.com/1532418/89916564-f58e5a00-dc21-11ea-9d01-1efd0e87b50b.png)![Tree Inventory 3](https://user-images.githubusercontent.com/1532418/89916573-f8894a80-dc21-11ea-9898-c47d0be325c4.png)![Saved Areas](https://user-images.githubusercontent.com/1532418/89916595-fe7f2b80-dc21-11ea-92ed-09bb1a0a4457.png)![Review 1](https://user-images.githubusercontent.com/1532418/89916644-10f96500-dc22-11ea-80ad-6bde3b49c034.png)![Review 2](https://user-images.githubusercontent.com/1532418/89916643-0fc83800-dc22-11ea-82a5-6102c5b5fe90.png)![Recension 1](https://user-images.githubusercontent.com/1532418/89916651-122a9200-dc22-11ea-8f1c-631feda3406e.png)![Recension 2](https://user-images.githubusercontent.com/1532418/89916647-1191fb80-dc22-11ea-95ec-541cab828671.png)

**Comment by sagararyal** [comment]
@norbertschuler I don't think it makes sense to implement translation in Alerts as we need to implement Error handling first.
Same with other screens which hasn't been fully completed. 

@captainamiedi will now perform ESlint fixes, and then we'll go over screen by screen to finalize changes.

**Comment by norbertschuler** [comment]
> Also, the only language that we need to support right now is Spanish, as we do expect some changes after initial test in the ground before adding other languages.

O.k., I just did the complete German translation as (1) it was quick & easy to do for me and (2) helped me to checked the completeness and correctness of the implementation of the translation :-)

> @captainamiedi will now perform ESlint fixes, and then we'll go over screen by screen to finalize changes.

Please be aware of https://github.com/Plant-for-the-Planet-org/treemapper/issues/24

**Comment by captainamiedi** [comment]
@norbertschuler Thanks for pointing these out. it seems i skipped some components. will make another PR to fix those  component except the alerts. When the PR is up, i will inform you for another checking.

**Comment by norbertschuler** [comment]
- [ ] Searching further missing translations I found https://github.com/Plant-for-the-Planet-org/treemapper/blob/develop/app/components/MultipleTrees/index.js and https://github.com/Plant-for-the-Planet-org/treemapper/blob/develop/app/components/Common/Accordian/index.js used within `MultipleTrees`, but I am not sure if this component is still used as I can find only a reference in https://github.com/Plant-for-the-Planet-org/treemapper/blob/develop/app/components/index.js? 

@ankitecd @tejassonar Do you have a good idea to check for unused components as I would like to avoid adding unused resources?
