### ISSUE TITLE
React on 401 code from API

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treemapper#154]
**Describe the bug**
When an authorized API request from the backend returns with status code 401 ("OAuth Token is invalid or expired"), the user should be either logged out or the OAuth Token should be refreshed from Auth0.

**Is it on a Production or Development Build?**
develop

**To Reproduce**
1. Open app after you have used it with a logged in user after some time (when your token is expired)
2. See error

**Screenshots**
<img width="952" alt="Bildschirmfoto 2021-01-22 um 16 57 54" src="https://user-images.githubusercontent.com/1532418/105513766-49d75300-5d05-11eb-8d16-89767251a523.png">

**Smartphone (please complete the following information):**
- Device: iPhone 11 simulator
- OS: iOS14.3
- Tree Mapper App Version 1.0.0

**Comment by norbertschuler** [comment]
- [ ] When I open the app I see an error message for the 401 error and when I click on my profile icon the app got stuck with a greyed screen:

![Simulator Screen Shot - iPhone 11 - 2021-01-22 at 17 00 07](https://user-images.githubusercontent.com/1532418/105514067-aaff2680-5d05-11eb-816f-bedba9b06bd5.png)![Simulator Screen Shot - iPhone 11 - 2021-01-22 at 17 00 11](https://user-images.githubusercontent.com/1532418/105514063-aa669000-5d05-11eb-9c21-d49340f4252a.png)

**Comment by sagararyal** [comment]
App is capable of requesting refresh token, so it should use the access token to fetch refresh token from Auth0 before sending user to login.

If fetching of refresh token fails, then the user can be logged out.
