### ISSUE TITLE
Uploading registered tree failed

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treemapper#156]
**Describe the bug**
The upload of a single registered tree to the develop backend failed with 400 error doing the following request:
`curl -H "Accept: application/json, text/plain, */*" -H "Content-Type: application/json" -H "Authorization: OAuth ***" -d "{\"captureMode\":\"on-site\",\"deviceLocation\":{\"coordinates\":[-122.0312186,37.33233141],\"type\":\"Punkt\"},\"geometry\":{\"type\":\"Punkt\",\"coordinates\":[-122.03121948242188,37.332332611083984]},\"plantDate\":\"2021-01-23T11:09:45.427Z\",\"registrationDate\":\"2021-01-23T11:09:45.427Z\",\"plantProject\":null,\"plantedSpecies\":[{\"otherSpecies\":\"Obetia carruthersiana\",\"treeCount\":1}]}" https://app-development.plant-for-the-planet.org/treemapper/plantLocations`
->
```json
{
  "code": 400,
  "message": "Validation Failed",
  "errors": {
    "children": {
      "plantProject": {
      },
      "deviceLocation": {
        "errors": [
          "The provided data is not a valid GeoJSON Point geometry."
        ]
      },
      "geometry": {
        "errors": [
          "The provided data must be a valid GeoJSON Point or Polygon geometry."
        ]
      },
      "plantDate": {
      },
      "registrationDate": {
      },
      "plantedSpecies": {
        "children": [
          {
            "children": {
              "treeCount": {
              },
              "otherSpecies": {
              },
              "species": {
              }
            }
          }
        ]
      },
      "captureMode": {
      }
    }
  }
}
```

**Is it on a Production or Development Build?**
develop

**To Reproduce**
1. Register a single tree
2. Upload it
3. See error

**Screenshots**
![Simulator Screen Shot - iPhone 11 - 2021-01-23 at 12 25 57](https://user-images.githubusercontent.com/1532418/105576878-81e3a200-5da8-11eb-9409-eb8c50a2d36b.png)

**Smartphone (please complete the following information):**
- Device: iPhone11 simulator
- OS: iOS14.3
- Tree Mapper App Version 1.0.0

**Comment by sagararyal** [comment]
type:
```
type\":\"Punkt\"},\"geometry\":{\"type\":\"Punkt\"
```

Geojson property Point is being translated, I think that is the error.
