### ISSUE TITLE
Download Maps not working

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treemapper#200]
**Describe the bug**
Currently the download of maps fail.

**Is it on a Production or Development Build?**
develop

**To Reproduce**
1. Go to Download Maps
2. Click to download
3. See error

**Screenshots**
![Simulator Screen Shot - iPhone 11 - 2021-02-11 at 10 48 02](https://user-images.githubusercontent.com/1532418/107624753-9bfffa00-6c5b-11eb-8cf7-2c7df148e36d.png)![Simulator Screen Shot - iPhone 11 - 2021-02-11 at 10 48 18](https://user-images.githubusercontent.com/1532418/107624755-9d312700-6c5b-11eb-9b99-974fb24c76fc.png)

**Smartphone (please complete the following information):**
- Device: iPhone 11 simulator
- OS: latest iOS
- Tree Mapper App Version: 1.0.0

**Comment by sagararyal** [comment]
Related to #188
