### ISSUE TITLE
p in MainActivity

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treemapper#208]
## Error in Tree Mapper

**p** in **MainActivity**
The user does not exist.

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/602cf71c4eea83001768dd92?event_id=602cf71c0069a689c2ad0000&i=gh&m=ci)

## Stacktrace

    [native code]:0 - Error

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/602cf71c4eea83001768dd92?event_id=602cf71c0069a689c2ad0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Cannot reproduce this error.

**Comment by Plant-for-the-Planet** [comment]
An error linked to this issue has been reopened in Bugsnag
[**p** in **&#91;native code&#93;:0**](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/602cf71c4eea83001768dd92?event_id=607ec94b0077c1eb8ad70000&i=gh&m=ra)

**Comment by norbertschuler** [comment]
Happening on signup.

**Comment by norbertschuler** [comment]
Bugsnag deleted the report, so we can not reproduce it anymore. Closing it.

**Comment by Plant-for-the-Planet** [comment]
An error linked to this issue has been reopened in Bugsnag
[**p** in **MainActivity**](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/602cf71c4eea83001768dd92?event_id=61019599007f9cea45430000&i=gh&m=ra)

**Comment by Plant-for-the-Planet** [comment]
An error linked to this issue has been reopened in Bugsnag
[**p** in **&#91;native code&#93;:0**](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/602cf71c4eea83001768dd92?event_id=61a662dc00896924969d0000&i=gh&m=ra)
