### ISSUE TITLE
java.lang.RuntimeException in AbstractStringBuilder.java:629

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treemapper#215]
## Error in Tree Mapper

**java.lang.RuntimeException** in **AbstractStringBuilder.java:629**
Could not invoke RNFSManager.readFile

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/602fe87eb616170017393c61?event_id=602fe87e006cc719314a0000&i=gh&m=ci)

## Stacktrace

    JavaMethodWrapper.java:383 - com.facebook.react.bridge.JavaMethodWrapper.invoke

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/602fe87eb616170017393c61?event_id=602fe87e006cc719314a0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
cannot reproduce
