### ISSUE TITLE
Login does not work on Android if Treecounter app installed

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treemapper#218]
**Describe the bug**
If the Treecounter app is installed on an Android device, the chrome browser doing the Auth0 login is opening the Treecounter app for the callback URL resulting into not being able to log into the Treemapper app. 
Info:
The Treecounter app registers for URL `trilliontreecampaign.org` and `accounts.plant-for-the-planet.org` where the later one is the problem.

**To Reproduce**
1. Try to login into the Treemapper app with the Treecounter app installed
2. See error

**Expected behavior**
Open the callback URL after login into the Treemapper app.

**What actually happens**
The Treecounter app is opened.

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Smartphone (please complete the following information):**
- Device: Google Nexus 7
- OS: Android 6
- Tree Mapper App Version: 1.0.0

**Comment by norbertschuler** [comment]
@sagararyal I need to update the file https://accounts.plant-for-the-planet.org/.well-known/assetlinks.json to allow the Treemapper app also to open the Auth0 callback links - as the domain `accounts.plant-for-the-planet.org` is directed to Auth0 can you tell me, where this file is hosted and can be updated?

**Comment by norbertschuler** [comment]
I am not sure if the Treecounter app needs to open an URL for `accounts.plant-for-the-planet.org` anymore at all as it's using one-time code login now instead of a full Auth0 login procedure. So maybe we can remove the support for this URL from the Treecounter app at https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/b8d2f5573983f28dc51104c2c22077ae10fb6a01/android/app/src/main/AndroidManifest.xml#L85-L89 so that if both apps are installed, the phone does not have to ask which one to open for the callback link.

The best solution of course would be to add an one-time code login to Treemapper as well and delete support for this URL at https://github.com/Plant-for-the-Planet-org/treemapper/blob/c6376b9af0c9ff6dd2fca30861b19e07b078929a/android/app/src/main/AndroidManifest.xml#L35-L38 as well, so that the login in a web browser of a mobile device is not disturbs by calling the apps when trying to login on the website on a mobile device!

**Comment by sagararyal** [comment]
@norbertschuler This has to be done through application settings. I've updated the key hash for Tree Mapper App. Please check.

Auth0 Dashboard > TreeMapper App > Settings > Advanced settings > Device Settings 

https://accounts.plant-for-the-planet.org/.well-known/assetlinks.json

**Comment by norbertschuler** [comment]
> https://accounts.plant-for-the-planet.org/.well-known/assetlinks.json

The SHA for the Treecounter app was removed, so I added it again once more. Looks good now.

**Comment by norbertschuler** [comment]
Just added a fix preventing registering any URL for the Android app: https://github.com/Plant-for-the-Planet-org/treemapper/commit/0a3d1b93ab188330daac0fd9a183d7618b6f3b00

**Comment by norbertschuler** [comment]
Probably working now.
