### ISSUE TITLE
EXC_BAD_ACCESS in mbgl::resourceURL(mbgl::Resource const&)

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treemapper#244]
## Error in Tree Mapper

**EXC_BAD_ACCESS** in **mbgl::resourceURL(mbgl::Resource const&)**
Attempted to dereference garbage pointer 0x3242f7ad7ae0.

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/6043dfc3e29b9d0017f8afef?event_id=6043dfc30072e7727fc80000&i=gh&m=ci)

## Stacktrace

    Frameworks/Mapbox.framework/Mapbox:0 - mbgl::resourceURL(mbgl::Resource const&)
    Frameworks/Mapbox.framework/Mapbox:0 - MGLStringFromMetricType
    Tree Mapper:0 - realm::util::FunctionRef<unsigned long (realm::BPlusTreeNode*, unsigned long)>::FunctionRef<realm::BPlusTree<realm::Decimal128>::erase(unsigned long)::{lambda(realm::BPlusTreeNode*, unsigned long)#1}&>(realm::BPlusTree<realm::Decimal128>::erase(unsigned long)::{lambda(realm::BPlusTreeNode*, unsigned long)#1}&)::{lambda(void*, realm::BPlusTreeNode*, unsigned long)#1}::__invoke(realm::BPlusTree<realm::Decimal128>::erase(unsigned long)::{lambda(realm::BPlusTreeNode*, unsigned long)#1}&, realm::BPlusTreeNode*, unsigned long)
    Tree Mapper:0 - _mh_execute_header

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/6043dfc3e29b9d0017f8afef?event_id=6043dfc30072e7727fc80000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Bugsnag deleted the report, so we can not reproduce it anymore. Closing it.
