### ISSUE TITLE
Centering location does not center to current location

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treemapper#274]
After loading map, centering location re-centers to initial location of the map, and not the the current location of the device.

https://user-images.githubusercontent.com/5401575/112733621-582e2f00-8f41-11eb-910c-dcd9b7247f54.MP4

**Comment by norbertschuler** [comment]
I can confirm this. The _map center icon_ always centers on the first location and not on my current own location. I would also expect to go to my current device location as this is what the users have learnt in all kind of maps applications. If we want to allow the user to quickly jump to the position of the first coordinate of the Polygon we should add another button with a different icon for that.
