### ISSUE TITLE
Problem with app update (data integrity)

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treemapper#275]
Updating App results location of single trees to return 0.000,0.000
v 1.0.0 to v.1.0.1 (current develop)

These trees were registered with v.1.0 but never uploaded.

![IMG_C614C845ECD8-1](https://user-images.githubusercontent.com/5401575/112733725-f02c1880-8f41-11eb-9711-d6d28c1485fd.jpeg)

**Comment by norbertschuler** [comment]
@ankitecd can the change from float to double for the Coordinates schema cause this issue at https://github.com/Plant-for-the-Planet-org/treemapper/blob/b5fe12b1e122570b3f85402a3409ce73aac2dfae/app/repositories/migrations/schema4.js#L5-L15 ?

**Comment by ankitecd** [comment]
> 
> 
> @ankitecd can the change from float to double for the Coordinates schema cause this issue at
> 
> https://github.com/Plant-for-the-Planet-org/treemapper/blob/b5fe12b1e122570b3f85402a3409ce73aac2dfae/app/repositories/migrations/schema4.js#L5-L15
> ?

Maybe I will check and fix this
