### ISSUE TITLE
EXC_BAD_ACCESS in Mapbox

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treemapper#289]
## Error in Tree Mapper

**EXC_BAD_ACCESS** in **Mapbox**
Attempted to dereference null pointer.

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/601a8b05209d4700170572b7?event_id=60659d670075ffc8bf4d0000&i=gh&m=ci)

## Stacktrace

    Frameworks/Mapbox.framework/Mapbox:0 - -[MGLMapView willResignActive:]
    Tree Mapper:0 - _mh_execute_header

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/601a8b05209d4700170572b7?event_id=60659d670075ffc8bf4d0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Maybe upgrade Mapbox?
