### ISSUE TITLE
Error in app/actions/UploadInventory.js:76 - Some image upload are pending

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treemapper#297]
## Error in Tree Mapper

**Error** in **app/actions/UploadInventory.js:76**
Some image upload are pending

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/60701356dfa19f00075c87b8?event_id=607013560077571b21a10001&i=gh&m=ci)

## Stacktrace

    app/actions/UploadInventory.js:76 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/60701356dfa19f00075c87b8?event_id=607013560077571b21a10001&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
This has happened together with the 401 error at #257
