### ISSUE TITLE
Bugs and Issues to Fix

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treemapper#31]
- [x] When tree details page is closed with `X` , take the user to Tree Inventory Page,
**Reopened**
On Review Page, when user clicks Save, --> user is taken to Tree Inventory --> user clicks Pending  Upload item --> user goes to Review Page --> User clicks  `X` button --> user is taken to Edit Location (map page)
This bug needs to be fixed, as user should not be able to edit location when X is clicked.
- [ ] Seems Map download is downloading more region than user has selected. (need to test) Or the  calculation is off by 10
instead of 740 mb it should probably show 7MB.
- [x] In Pending Upload Items, tapping Pending upload (Single Tree registration) takes to Map page allowing user to edit the coordinate. This should  not be possible. Instead the user should be sent to Review page without  option to edit the coordinates, or details.

- [x] Image Upload error (Single Tree) Staging Backend

App needs to be able to handle these errors. App is still stuck at Uploading...
<img width="1390" alt="Screen Shot 2020-08-05 at 8 49 56 PM" src="https://user-images.githubusercontent.com/5401575/89452029-5834b100-d75d-11ea-9022-7b0d3fdbc168.png">

- [x] When  user clicks Upload Now; or when user is connected to Wifi,  upload should happen in the background without showing the  pop-up /overlay. If an upload fails, the items should simply changes the cloud icon to grey and it should be tried again for upload after some interval.

- [x] If for any reason upload is partially complete, the app should store the response and be able to only send the remaining data to the server. Currently the app sends the inventory item as a new item. In this case, the plant location response should be stored, and the  app should retry to only  upload the images that haven't been previously uploaded. Please check google photos to see how uploads are handled.

<img width="1004" alt="Screen Shot 2020-08-05 at 8 55 32 PM" src="https://user-images.githubusercontent.com/5401575/89452566-28d27400-d75e-11ea-82d4-0a0ba302b271.png">

- [x] Current Date selector is not intuitive 
Please change as below: the screenshot on right is from Compete from main plant-for-the-planet app
**Reopened**
For example the available date is win 2021 + beyond. The dates available in Offsite, should be before today [in the past] not in the future. 
![IMG_2F4DEDC6358F-1](https://user-images.githubusercontent.com/5401575/89433898-2dd5fa00-d743-11ea-8d01-d24f2d2b28b5.jpeg)
- [x] Clicking back arrow from Tree Inventory Page puts the user in infinite loop of edit screens.
It should take the user back to Landing page.
**Not yet fixed in the  latest release**

- [ ] Off Site Polygon, – Allows to complete with two coordinates and makes C, D same as A . This should only be  possible when you are at location C.
- [x] If a registration type does not have an image, show map image.
- [x] Auto upload Inventory Items when connected to WiFi  if uploadOnWiFi = true [this flag can be set on profile popup; will provide a UI]

- [x] Do not show "View All Uploaded Items" button if at least one item hasn't been fully been uploaded.

- [x] In Location type (Multiple trees: Single Coordinate) Alrighty screen  appears after selecting location. This should be disabled.

- [x] Disable Alrighty screen at the beginning of the process for Coordinate A  [Please refer to Flows in Design]
- [x] List of Planted Species are not cleared for a new registration. Currently preselected species from different registration are selected with the count. For each new registration this should be different.

- [x] Implement design change for Planted Species to show Local Name & Scientific Name (refer to designs)

- [x] Remove marker from Download map pages.
![IMG_EF06C4F1F545-1](https://user-images.githubusercontent.com/5401575/88784919-de1a9000-d190-11ea-8b30-ad9a21b5b874.jpeg)

## Design change in Tree Inventory List
<img width="315" alt="Screen Shot 2020-07-29 at 10 27 24 AM" src="https://user-images.githubusercontent.com/5401575/88776328-19639180-d186-11ea-89ba-3aac2e18b0ac.png">

- [x] If species are selected, show sum of all planted species. (currently it shows only count of first species)

- [x] In Uploaded Items, currently, count ≠ sum of all species, this needs to be sum of all selected species.

- [x] If species are not selected, [check with Jorgo if it is possible to submit without a Tree Count.] Otherwise make it mandatory  before marking a record completed.

- [x] If On Site registration with images have pending images to be uploaded, do not move them to "uploaded items" and still mark pending upload.

- [x] Remove width eg( 10 cm) from entry in Pending Upload.  and instead add [ Tree Count, Reg Type and Date] as in design below

<img width="650" alt="Screen Shot 2020-07-29 at 10 42 12 AM" src="https://user-images.githubusercontent.com/5401575/88777987-30a37e80-d188-11ea-9c7f-73355574466b.png">

- [x] Once Item has been uploaded, move them to Uploaded List (new page) and remove them from device in 30 days.

- [x] Add option to Free Up Space  – Delete all fully uploaded registrations from device. 

- [x] Show message to remind user that the feature to download this list does not currently exist.
<img width="465" alt="Screen Shot 2020-07-29 at 10 45 20 AM" src="https://user-images.githubusercontent.com/5401575/88778316-ab6c9980-d188-11ea-91bf-9bd031f1c09b.png">

- [x] Singe  Tree (Pending) Fix 1 Tree instead of 1 "Null" tree
![IMG_97D3852CBA81-1](https://user-images.githubusercontent.com/5401575/88982132-c560c600-d2c7-11ea-82c8-90d1eca95660.jpeg)

## Login

- [x] #32 is related to a Crash when Log out is pressed.

**Comment by sagararyal** [comment]
- [ ] Clicking Add Area does not take user to map page.

- [ ] Seems Map download is downloading more region than user has selected. (need to test) Or the  calculation is off by 10
instead of 740 mb it should probably show 7MB.

**Comment by sagararyal** [comment]
- [ ] Auth0 Domain for Test and Production are different. Implement a way to access env variable in AndroidManifest.xml

<img width="1000" alt="Screen Shot 2020-08-04 at 5 24 05 PM" src="https://user-images.githubusercontent.com/5401575/89312430-88a21f80-d677-11ea-86a9-345483a994b7.png">
https://stackoverflow.com/questions/58912959/access-environment-variable-in-react-native-androidmanifest-xml

**Comment by norbertschuler** [comment]
> * [ ]  Auth0 Domain for Test and Production are different. Implement a way to access env variable in AndroidManifest.xml

The solution used in the TreecounterApp is quite o.k. for using different .env.* files for develop, production and other environment for React-Native (using react-native-config), Android (adding some stuff to build.gradle) and iOS (building custom schemes).

**Comment by norbertschuler** [comment]
> > * [ ]   Auth0 Domain for Test and Production are different. Implement a way to access env variable in AndroidManifest.xml
> 
> The solution used in the TreecounterApp is quite o.k. for using different .env.* files for develop, production and other environment for React-Native (using react-native-config), Android (adding some stuff to build.gradle) and iOS (building custom schemes).

I assume I would have to remove https://www.npmjs.com/package/react-native-dotenv (old version 0.2.0 is used) and add https://www.npmjs.com/package/react-native-config instead in order to have better .env support also for Android and iOS. As that’s a bigger change of the apps architecture, I will have to start a new branch for it.
