### ISSUE TITLE
TypeError in node_modules/whatwg-fetch/dist/fetch.umd.js:535 - Network request failed

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treemapper#317]
## Error in Tree Mapper

**TypeError** in **node_modules/whatwg-fetch/dist/fetch.umd.js:535**
Network request failed

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/608c3c32e071220007785f09?event_id=608c3c320079da625dc00000&i=gh&m=ci)

## Stacktrace

    node_modules/whatwg-fetch/dist/fetch.umd.js:535 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/608c3c32e071220007785f09?event_id=608c3c320079da625dc00000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by Plant-for-the-Planet** [comment]
An error linked to this issue has been reopened in Bugsnag
[**TypeError** in **node_modules/whatwg-fetch/dist/fetch.umd.js:535**](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/608c3c32e071220007785f09?event_id=61018bdd007f93714e7f0000&i=gh&m=ra)

**Comment by Plant-for-the-Planet** [comment]
An error linked to this issue has been reopened in Bugsnag
[**TypeError** in **node_modules/whatwg-fetch/dist/fetch.umd.js:535**](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/608c3c32e071220007785f09?event_id=61b7d305008aa50b90820000&i=gh&m=ra)

**Comment by dilas12345** [comment]
Have this issue been resolved, i am also facing same issue, and i have even tried switching from using fetch to axios still facing same, before then i have also followed a documentation on changing the URL and port, maybe there could port conflict, i have done that and i am still having same issue, i really need help here. by the way i am facing this issue with expo and my backend is laravel
