### ISSUE TITLE
undefined is not an object (evaluating 'we.coords') at app/components/Common/MapMarking/index.js:277 

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treemapper#328]
## Error in Tree Mapper

**TypeError** in **MainActivity**
undefined is not an object (evaluating 'we.coords')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/609fe4fd1386fd00079eac08?event_id=609fe4fd007c54fd07380000&i=gh&m=ci)

## Stacktrace

    app/components/Common/MapMarking/index.js:277 - 
    app/components/Common/MapMarking/index.js:276 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/609fe4fd1386fd00079eac08?event_id=609fe4fd007c54fd07380000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
<img width="853" alt="Bildschirmfoto 2021-05-29 um 16 57 38" src="https://user-images.githubusercontent.com/1532418/120074827-028c1500-c09f-11eb-907f-6a03188978c9.png">
