### ISSUE TITLE
Error at app/repositories/species.js:15

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treemapper#329]
## Error in Tree Mapper

**Error** in **MainActivity**
Attempting to create an object of type 'ScientificSpecies' with an existing primary key value ''sspec_7E82XsO3Jt0RByrnGu''.

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/60a2f192a156ec00077e881f?event_id=60a2f192007c8e8aeb6e0000&i=gh&m=ci)

## Stacktrace

    app/repositories/species.js:15 - 
    app/repositories/species.js:14 - 
    app/repositories/species.js:13 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/60a2f192a156ec00077e881f?event_id=60a2f192007c8e8aeb6e0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
<img width="790" alt="Bildschirmfoto 2021-05-29 um 17 00 06" src="https://user-images.githubusercontent.com/1532418/120074909-5c8cda80-c09f-11eb-8e31-0a3ae46660e4.png">
