### ISSUE TITLE
undefined is not an object (evaluating 'we.coords') at app/components/Common/MapMarking/index.js:367

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treemapper#345]
## Error in Tree Mapper

**TypeError** in **MainActivity**
undefined is not an object (evaluating 'we.coords')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/60abaef304b3f00007cefee6?event_id=60abaef3007ca850658d0000&i=gh&m=ci)

## Stacktrace

    app/components/Common/MapMarking/index.js:367 - 
    app/components/Common/MapMarking/index.js:366 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/60abaef304b3f00007cefee6?event_id=60abaef3007ca850658d0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
<img width="740" alt="Bildschirmfoto 2021-05-29 um 17 03 13" src="https://user-images.githubusercontent.com/1532418/120075001-cd33f700-c09f-11eb-8484-99ff9e42d156.png">
