### ISSUE TITLE
undefined is not an object (evaluating 'Oe.coords') in app/components/Common/MapMarking/index.js:276

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treemapper#346]
## Error in Tree Mapper

**TypeError** in **app/components/Common/MapMarking/index.js:276**
undefined is not an object (evaluating 'Oe.coords')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/60abb41ca8a0330007c13442?event_id=60abb41c007c9c316e340000&i=gh&m=ci)

## Stacktrace

    app/components/Common/MapMarking/index.js:276 - 
    app/components/Common/MapMarking/index.js:275 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/60abb41ca8a0330007c13442?event_id=60abb41c007c9c316e340000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
<img width="722" alt="Bildschirmfoto 2021-05-29 um 17 05 12" src="https://user-images.githubusercontent.com/1532418/120075062-0cfade80-c0a0-11eb-84d6-db86c0fd913f.png">
