### ISSUE TITLE
Export Logs

### ISSUE THREAD

**Issue by tejassonar** [Plant-for-the-Planet-org/treemapper#351]
**Describe the feature you'd like to see included in Tree Mapper App.**
- Export logs in .txt or .log format

**Comment by norbertschuler** [comment]
We can copy the export functionality from here: https://github.com/Plant-for-the-Planet-org/treemapper/blob/8fe00c0183ca3f29e69257cfe86b5c005d8ba7d0/app/components/InventoryOverview/index.js#L262-L289
