### ISSUE TITLE
Error in app/repositories/species.js:324 (app crashes for too big images) - String too big 

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treemapper#361]
## Error in Tree Mapper

**Error** in **MainActivity**
String too big
Exception backtrace:
<backtrace not supported on this platform>

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/60ba1e3087a43c0007afc73c?event_id=60ba1e30007d1294448f0000&i=gh&m=ci)

## Stacktrace

    app/repositories/species.js:324 - 
    app/repositories/species.js:313 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/60ba1e3087a43c0007afc73c?event_id=60ba1e30007d1294448f0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
<img width="650" alt="Bildschirmfoto 2021-06-04 um 14 48 33" src="https://user-images.githubusercontent.com/1532418/120803550-f4794100-c543-11eb-8611-0f89d2c0743e.png">

**Comment by norbertschuler** [comment]
Device used was HUAWEI P30 (ELE-L29)
