### ISSUE TITLE
ReferenceError in app/Components/Common/index.js:11 - Can't find variable: API_ENDPOINT

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treemapper#38]
## Error in Tree Mapper

**ReferenceError** in **app/Components/Common/index.js:11**
Can't find variable: API_ENDPOINT

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/5f2a61c4340f88001887efd4?event_id=5f2a61c4005b7d59a5470000&i=gh&m=ci)

## Stacktrace

    app/Components/Common/index.js:11 - 
    app/Components/RegisterTree/index.js:3 - 
    app/Components/index.js:16 - 
    app/Components/App/index.js:6 - 
    index.js:2 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/5f2a61c4340f88001887efd4?event_id=5f2a61c4005b7d59a5470000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by captainamiedi** [comment]
These error can't be reproduce and cant be found from the details or stacktrace
