### ISSUE TITLE
Error in node_modules/invariant/browser.js:39 - Module AppRegistry is not a registered callable module (calling runApplication)

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treemapper#39]
## Error in Tree Mapper

**Error** in **node_modules/invariant/browser.js:39**
Module AppRegistry is not a registered callable module (calling runApplication)

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/5f2a61c5fce1c7001765ca15?event_id=5f2a61c5005b7404b25b0000&i=gh&m=ci)

## Stacktrace

    node_modules/invariant/browser.js:39 - exports

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/5f2a61c5fce1c7001765ca15?event_id=5f2a61c5005b7404b25b0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by captainamiedi** [comment]
can replicate these error on development.
