### ISSUE TITLE
Error in app/repositories/species.ts:70 - scientificName BEGINSWITH[c] 'Robom'':1:36(36): Invalid predicate

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treemapper#443]
## Error in Tree Mapper

**Error** in **MainActivity**
scientificName BEGINSWITH[c] 'Robom'':1:36(36): Invalid predicate.

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/61019ebd3f78110008ef698e?event_id=61019ebd007f938cc1900000&i=gh&m=ci)

## Stacktrace

    app/repositories/species.ts:70 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/61019ebd3f78110008ef698e?event_id=61019ebd007f938cc1900000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
<img width="710" alt="Bildschirmfoto 2021-09-09 um 09 12 48" src="https://user-images.githubusercontent.com/1532418/132639936-6d1e2f0d-9361-4084-9846-1919541b3294.png">
