### ISSUE TITLE
Error in app/repositories/additionalData.ts:434 - objectType cannot be empty

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treemapper#478]
## Error in Tree Mapper

**Error** in **MainActivity**
objectType cannot be empty

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/6139b31e68521d00077ea0f7?event_id=6139b31e00809bb3f7c30000&i=gh&m=ci)

## Stacktrace

    app/repositories/additionalData.ts:434 - 
    app/repositories/additionalData.ts:429 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/6139b31e68521d00077ea0f7?event_id=6139b31e00809bb3f7c30000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
<img width="796" alt="Bildschirmfoto 2021-09-09 um 09 11 33" src="https://user-images.githubusercontent.com/1532418/132639755-5a9c0947-c36d-4ce2-b860-f999e522b85e.png">
