### ISSUE TITLE
TypeError in app/repositories/inventory.js:965 - undefined is not an object (evaluating '(_=o.objectForPrimaryKey('ScientificSpecies',""+E)).aliases')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treemapper#479]
## Error in Tree Mapper

**TypeError** in **app/repositories/inventory.js:965**
undefined is not an object (evaluating '(_=o.objectForPrimaryKey('ScientificSpecies',""+E)).aliases')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/6139be9567efea000731a98d?event_id=6139be950080a7d089c00000&i=gh&m=ci)

## Stacktrace

    app/repositories/inventory.js:965 - 
    app/repositories/inventory.js:937 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/6139be9567efea000731a98d?event_id=6139be950080a7d089c00000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Amount of errors decreased, so removing priority label.
