### ISSUE TITLE
Error in [native code]: Out of memory & Value 'Invalid Date' not convertible to a number

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treemapper#511]
## Error in Tree Mapper

**Error** in **[native code]:0**

1. Out of memory
<img width="507" alt="Bildschirmfoto 2022-01-22 um 12 45 47" src="https://user-images.githubusercontent.com/1532418/150637245-a36c479c-7808-4b29-8f39-14d6806394b1.png">

2. Value 'Invalid Date' not convertible to a number
<img width="665" alt="Bildschirmfoto 2022-01-22 um 12 47 59" src="https://user-images.githubusercontent.com/1532418/150681323-8c4e7530-5ec0-4718-a24d-aefd7c2a2996.png">

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/617d74ff3d0e69000859d934?event_id=6198712100897a09dec40000&i=gh&m=ci)

## Stacktrace

    [native code]:0 - stringify

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/617d74ff3d0e69000859d934?event_id=6198712100897a09dec40000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
![image](https://user-images.githubusercontent.com/1532418/142720207-b00d8a56-765d-430b-8efc-be623372d5c4.jpeg)

**Comment by norbertschuler** [comment]
Maybe the amount of existing registrations of Yucatán are causing memory problems when loading them from the backend to Android devices?

**Comment by norbertschuler** [comment]
Bugsnag mixed up this issue with another error `Value 'Invalid Date' not convertible to a number` caused by the backend.
