### ISSUE TITLE
Exception in unknown method

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treemapper#520]
## Error in Tree Mapper

**Exception** in **unknown method**

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/619bc89494a294000870e773?event_id=619bc89400896a51bca10000&i=gh&m=ci)

## Stacktrace

    unknown file:0 - unknown method

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/619bc89494a294000870e773?event_id=619bc89400896a51bca10000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
completely unproducable
