### ISSUE TITLE
TypeError in app/repositories/projects.ts:90 - undefined is not a function (near '...t.forEach...')

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treemapper#521]
## Error in Tree Mapper

**TypeError** in **MainActivity**
undefined is not a function (near '...t.forEach...')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/619bfb5048d5ab000785c9fe?event_id=619bfb500089602b27280000&i=gh&m=ci)

## Stacktrace

    app/repositories/projects.ts:90 - 
    app/repositories/projects.ts:89 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/619bfb5048d5ab000785c9fe?event_id=619bfb500089602b27280000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
![image](https://user-images.githubusercontent.com/1532418/142933399-c7a1b8fd-1a60-41b1-9cf3-b40892093641.jpeg)
