### ISSUE TITLE
Error in app/utils/api.ts:147 - Out of memory

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treemapper#529]
## Error in Tree Mapper

**Error** in **app/utils/api.ts:147**
Out of memory

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/61a0bf6048b5bb0007e34b34?event_id=61a0bf6000897bb725ec0000&i=gh&m=ci)

## Stacktrace

    app/utils/api.ts:147 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/61a0bf6048b5bb0007e34b34?event_id=61a0bf6000897bb725ec0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
<img width="718" alt="Bildschirmfoto 2021-11-26 um 12 17 04" src="https://user-images.githubusercontent.com/1532418/143572934-7bf08529-0804-476e-80fe-eed1093b2b4a.png">
