### ISSUE TITLE
Error in app/actions/UploadInventory.js:618 - Out of memor

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treemapper#530]
## Error in Tree Mapper

**Error** in **app/actions/UploadInventory.js:618**
Out of memory

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/61a0bfcc06897e000714d9be?event_id=61a0bfcc0089618c6c4b0000&i=gh&m=ci)

## Stacktrace

    app/actions/UploadInventory.js:618 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/61a0bfcc06897e000714d9be?event_id=61a0bfcc0089618c6c4b0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
<img width="718" alt="Bildschirmfoto 2021-11-26 um 12 17 46" src="https://user-images.githubusercontent.com/1532418/143573021-e64b3c50-1fbb-47fb-bfb4-7d2b13fa90dc.png">
