### ISSUE TITLE
java.lang.UnsatisfiedLinkError in NativeConnectivityListener.java:27

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treemapper#552]
## Error in Tree Mapper

**java.lang.UnsatisfiedLinkError** in **NativeConnectivityListener.java:27**
No implementation found for void com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize() (tried Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize and Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize__)

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/61c5f8f231724f000755a705?event_id=61c5f8f2008aa0a861ca0000&i=gh&m=ci)

## Stacktrace

    NativeConnectivityListener.java:-2 - com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/61c5f8f231724f000755a705?event_id=61c5f8f2008aa0a861ca0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by noorulNA** [comment]
Fatal Exception: java.lang.UnsatisfiedLinkError
No implementation found for void com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize() (tried Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize and Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize__) how to fix this issue in mapbox v9
