### ISSUE TITLE
UI Flow in Single Tree Registration

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treemapper#65]
Single Tree Registration currently does not allow selecting species stored in the  user profile or locally on device.
This UI simplifies the process

<img width="984" alt="Screen Shot 2020-08-15 at 10 31 28 AM" src="https://user-images.githubusercontent.com/5401575/90308845-28b34080-dee3-11ea-80e4-bbfaf83e8926.png">

Depending on On Site/ Off Site registration; user should be  redirected to 

1.  Select Species Page [This page has currently been implemented in Multiple Trees Review Page]
2. When the user clicks Save and Continue, show an overlay asking for the diameter of the  tree.
3. When the diameter [mandatory field] is entered take the user to Review Page which contains [small design changes].

**Comment by norbertschuler** [comment]
@sagararyal can we close this?
