### ISSUE TITLE
TypeError in TypeError: undefined is not a function:0

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treemapper#689]
## Error in Tree Mapper

**TypeError** in **TypeError: undefined is not a function:0**
undefined is not a function

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/64cf2e98037514000828da91?event_id=64cf2e9700bec54c8b490000&i=gh&m=ci)

## Stacktrace

    TypeError: undefined is not a function:0 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/64cf2e98037514000828da91?event_id=64cf2e9700bec54c8b490000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Resolved
