### ISSUE TITLE
Internet Check

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treemapper#73]
When the app is offline and has pending uploads it should check for Internet frequently.

Folks at Forest Watcher have integrated offline mode check on react-native. Please check if it is still relevant; 
https://github.com/forest-watcher/forest-watcher/pull/314
https://github.com/forest-watcher/forest-watcher/blob/master/app/offline/detectNetwork.js

A similar approach could be  taken with a  decay schedule eg:
https://github.com/forest-watcher/forest-watcher/blob/master/app/offline/retry.js

**Comment by norbertschuler** [comment]
For me it looks like how a npm module [@redux-offline/redux-offline](https://github.com/redux-offline/redux-offline) was configured and extended. (Besides the Forest Watcher project is still using react-native 0.59.10 and @redux-offline/redux-offline 2.5.1 which is already a little outdate from 2018).
