### ISSUE TITLE
Login with Auth0 [WIP]

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treemapper#8]
We'll use API -Key authentication for Follow up requests, eg, registering trees, uploading images, etc.

However the app will need to login using Auth0 [with TPO or any Plant-for-the-Planet Account] and retrieve the API Key.
If a user does not have an account, let them complete sign up; confirm their email; and retrieve API Key; store locally.

--

API Key can be invalidated/reset without the client knowing.  
The client could know this via error when tree registration is uploaded. In this case the  app should prompt the user to login, and gracefully store and save the inventory items locally without deleting.

@jmiridis @haideralishah  please have a call to discuss fallback methods.

------
Todo:

- [x] Enable Login/ Signup

----

https://auth0.com/docs/universal-login/new

Guide: https://auth0.com/blog/developing-modern-apps-with-symfony-and-react/

Docs (Backend) https://treecounter-docs.herokuapp.com/system/authentication/ClientAPIAuthentication.html#auth0-flow

------
Do not use Deprecated Lock Method

**Comment by jmiridis** [comment]
## Authentication Implementation

#### Motivation

One of the main purposes of the TreeInventory app, is to create trust between all participants. The information captured must therefore not only be verifiable but also fake-proof. 
This requires
- the user that performs the operation to be who he says he is (authentication)
- the prevention of API calls by network tools other than the actual app (at least for on-site registration)

The situation, that a device used on-site will have no internet access for long periods and therefore cannot update a JWT before the refresh token expires, must also be taken into consideration.

### Authentication

The proposed authentication system is divided into 2 parts:
- authentication via Auth0 (sign-up / sign-in)
- retrieval of an API key to be used for API calls to the server

**Comment by sagararyal** [comment]
Pending Signup; and Login with Refreshtokens
Related to: #37
