### ISSUE TITLE
Camera capture failed. Camera is already capturing

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treemapper#87]
## Error in Tree Mapper

**Error** in **MainActivity**
Camera capture failed. Camera is already capturing.

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/5f73593bc5cd130018e234dc?event_id=5f73593b0060b3bd8e9f0000&i=gh&m=ci)

## Stacktrace

    node_modules/@babel/runtime/helpers/extends.js:19 - 

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/tree-mapper/errors/5f73593bc5cd130018e234dc?event_id=5f73593b0060b3bd8e9f0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Bugsnag bug already expired.
